#!/usr/bin/env python

import sys
import re
import subprocess
import os

#
# Helper functions
#
def get_ssh_server ():
	return os.getenv('SSH_SERVER', "localhost")

def substitute_parameters (text):
	pattern = re.compile(r"%%(.*?)%%")
	return re.sub(pattern, substitute_parameter, text)

def substitute_parameter (m):
	parameter = m.group(1)
	if parameter.startswith("creditentials."):
		creditentials = parameter.split(".")
		proc = subprocess.Popen(
			[
				"ssh",
				get_ssh_server(),
				"getcreditentials",
				creditentials[1],
				creditentials[2]
			],
			stdout=subprocess.PIPE
		)
		(out, err) = proc.communicate()
		return out.strip()

	sys.stderr.write("Unknown parameter: " + parameter)
	return ""

#
# Procedural code
#

if len(sys.argv) != 2:
	print "Usage: genconfig <template file>"
	sys.exit(1)

with open(sys.argv[1]) as f:
	for line in f:
		print substitute_parameters(line),
